[book]
authors = ["NixOS Brasil <https://github.com/nixosbrasil>"]
language = "en"
title = "Modular Generated Command Line Interfaces"

[output]

[output.html]
edit-url-template = "https://github.com/nixosbrasil/climod/edit/master/docs/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/nixosbrasil/climod"
no-section-label = true
site-url = "/climod/"

[output.html.fold]
enable = true
